# Generated by Django 4.2 on 2023-06-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='V_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_model', models.CharField(max_length=100)),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.make')),
            ],
        ),
    ]
