# Generated by Django 4.2 on 2023-06-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='area',
            field=models.CharField(default='Richwood', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='postal',
            field=models.CharField(default='7441', max_length=50),
            preserve_default=False,
        ),
    ]
