# Generated by Django 4.2 on 2023-06-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_company_area_company_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.company')),
                ('serviced_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.vehicle')),
            ],
        ),
    ]
