# Generated by Django 4.2 on 2023-06-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviced_at',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
