# Generated by Django 4.2 on 2023-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_serviced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_no',
            field=models.CharField(default='CA', max_length=15),
            preserve_default=False,
        ),
    ]
